plugins {
    id 'eclipse'
    id 'net.neoforged.moddev' version '2.0.95'
}

repositories {
    maven {
        name = "Refined Storage"
        url = uri("https://maven.creeperhost.net")
        content {
            includeGroup("com.refinedmods.refinedstorage")
        }
    }
}

version = '0.1.4'
base.archivesName = "refinedflowanalytics"

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = "21.1.255"

    runs {
        client {
            client()
        }
        server {
            server()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        refinedflowanalytics {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    api "com.refinedmods.refinedstorage:refinedstorage-neoforge:${refinedstorage_version}"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
