org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
neo_version=21.1.255

refinedstorage_version=2.0.9

mod_id=refinedflowanalytics
mod_version=1.21.1-1.0.0
current_changelog=- Initial version