org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn

modVersion=26.1.2-2.0.0
modid=refinedflowanalytics
currentChangelog=- 26.1.2 port
refinedarchitectVersion=1.7.1
refinedstorageVersion=3.2.1
minecraftVersion=26.1.2
