- Update Inflow/Outflow graphic to look like (https://chatgpt.com/g/g-p-699b0b73f3d88191b94680788ee8dc03-yavuz/c/6ac29609-a4f4-83eb-86ee-48ece48f2adf): ✅
        Inflow
 +3000 ┤        ╭──────╮
 +2000 ┤   ╭────╯      ╰───
 +1000 ┤───╯
     0 ┼────────────────────────  Net = 0
 -1000 ┤───╮
 -2000 ┤   ╰────╮      ╭───
 -3000 ┤        ╰──────╯
        Outflow

- Throughput monitor block (shows live graph or current change outside like storage monitor block)
- Add throughput to Network Monitor (the new analytic tool raoul is working on)
- Flow Detector (give redstone signal on specific if cases)
- Leaving and joining into world counts as inflow, fix (Only for recently changed resources?) ✅
- Total resource inflow/outflow view