@ParametersAreNonnullByDefault
@FieldsAndMethodsAreNonnullByDefault
package com.ultramega.refinedflowanalytics.datagen.tag;

import com.refinedmods.refinedstorage.api.core.FieldsAndMethodsAreNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
