modLoader="javafml"
loaderVersion="[4,)"
license="GPL"

[[mods]]
modId="refinedflowanalytics"
version="${version}"
displayName="Refined Flow Analytics"
displayURL="https://github.com/starforcraft/Refined-Flow-Analytics"
logoFile="logo.png"
authors="Ultramega, XaMi"
description="Track and visualize resource movement within your Refined Storage network!"

[[mixins]]
config="refinedflowanalytics.mixins.json"

[[dependencies.refinedflowanalytics]]
    modId="neoforge"
    type="required"
    versionRange="[26.1.2.78,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.refinedflowanalytics]]
    modId="minecraft"
    type="required"
    versionRange="[26.1.2]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.refinedflowanalytics]]
    modId="refinedstorage"
    type="required"
    versionRange="[3.2.1,)"
    ordering="NONE"
    side="BOTH"
